load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "future",
    srcs = ["future.go"],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = ["@com_github_pkg_errors//:errors"],
)

go_test(
    name = "future_test",
    srcs = ["future_test.go"],
    deps = [
        ":future",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
