load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "data",
    srcs = [
        "binary.go",
        "list.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/common/data",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/common/sync/bufferpool",
        "@com_github_spf13_afero//:afero",
    ],
)

go_test(
    name = "data_test",
    srcs = ["binary_test.go"],
    embed = [":data"],
    deps = [
        "@com_github_spf13_afero//:afero",
        "@com_github_stretchr_testify//assert",
    ],
)
