load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "prometheus",
    srcs = ["prometheus.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export/prometheus",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/core",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export/metric",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/label",
    ],
)
