load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "lcs",
    srcs = [
        "common.go",
        "doc.go",
        "labels.go",
        "old.go",
        "sequence.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/gotoolsinternal/diff/lcs",
    visibility = ["//visibility:public"],
)

go_test(
    name = "lcs_test",
    srcs = [
        "common_test.go",
        "old_test.go",
    ],
    embed = [":lcs"],
)
