load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "persistent",
    srcs = [
        "map.go",
        "set.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/internal/gopls/pkg/util/constraints"],
)

go_test(
    name = "persistent_test",
    srcs = [
        "map_test.go",
        "set_test.go",
    ],
    embed = [":persistent"],
    deps = ["//pkg/poolside-helper/internal/gopls/pkg/util/constraints"],
)
