# gazelle:prefix github.com/poolsideai/assistant
__POOL_SYNTHETIC_IMPORT_BASELINE__
# gazelle:exclude scripts

load("@buildifier_prebuilt//:rules.bzl", "buildifier")
load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@rules_go//go:def.bzl", "TOOLS_NOGO", "nogo")
load("//:bazel/staticcheck_deps.bzl", "STATICCHECK_DEPS")

nogo(
    name = "nogo",
    config = "//:nogo_config.json",
    visibility = ["//visibility:public"],
    deps = STATICCHECK_DEPS + TOOLS_NOGO + [
        "@com_github_gordonklaus_ineffassign//pkg/ineffassign",
    ],
)

gazelle_binary(
    name = "gazelle_bin",
    languages = ["@gazelle//language/go:go_default_library"],
)

gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
)

# This test target was replaced by `make test-ci`.
# It runs all the tests with the tag "test_ci" as a stop-gap
# solution, as many other tests tagged with "integration" are
# failing (and/or may require more setup).
# See rationale in #33040
#
# test_suite(
#    name = "integration_tests",
#    # ...
#)

buildifier(
    name = "buildifier.check",
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
    lint_mode = "warn",
    mode = "check",
)

buildifier(
    name = "buildifier.format",
    exclude_patterns = [
        "./.git/*",
__POOL_SYNTHETIC_IMPORT_BASELINE__
    ],
    lint_mode = "fix",
    mode = "fix",
    verbose = True,
)
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
