__POOL_SYNTHETIC_IMPORT_BASELINE__
import type { ACPConversationStatusRepository } from "../acp";
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
export function setElicitationContext(conversationStatus: ACPConversationStatusRepository) {
  return setContext(new ElicitationRepository(conversationStatus));
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
