load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "glob",
__POOL_SYNTHETIC_IMPORT_BASELINE__
    srcs = ["glob.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/pkg/test/integration/fake/glob",
    visibility = ["//visibility:public"],
)

go_test(
    name = "glob_test",
    srcs = ["glob_test.go"],
    deps = [":glob"],
)
