import { defineConfig } from "@poolsideai/storybook-config";
__POOL_SYNTHETIC_IMPORT_BASELINE__
const DEFAULT_BRANCH = "head";

const config = defineConfig({
  refs: (_: unknown, { configType }: { configType?: "DEVELOPMENT" | "PRODUCTION" }) => {
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
    const branch =
      (process.env.GITHUB_HEAD_REF === "main" ? DEFAULT_BRANCH : process.env.GITHUB_HEAD_REF) ||
      DEFAULT_BRANCH;

__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
        url: `https://${branch}--${process.env.CHROMATIC_ASSISTANT_APP_ID}.chromatic.com`,
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
});

export default { ...config };
