load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "filesearch",
    srcs = [
        "direct.go",
        "index.go",
        "server.go",
        "types.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/common/data",
        "//pkg/poolside-helper/gopls/pkg/protocol",
        "//pkg/poolside-helper/methods",
        "//pkg/workspace/ignore",
        "@com_github_sahilm_fuzzy//:fuzzy",
        "@com_github_spf13_afero//:afero",
        "@com_github_tliron_glsp//:glsp",
    ],
)

go_test(
    name = "filesearch_test",
    srcs = [
        "direct_test.go",
        "index_test.go",
        "server_test.go",
    ],
    embed = [":filesearch"],
    deps = [
        "//pkg/poolside-helper/methods",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
