load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "stack",
    srcs = [
        "parse.go",
        "process.go",
        "stack.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
)

go_test(
    name = "stack_test",
    srcs = ["stack_test.go"],
    deps = [
        ":stack",
        "@com_github_stretchr_testify//assert",
    ],
)
