load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "git",
    srcs = [
        "diff_stream.go",
        "git.go",
        "handler.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/handler/git",
    visibility = ["//pkg/poolside-helper:__subpackages__"],
    deps = [
        "//pkg/poolside-helper/methods",
        "@com_github_pkg_errors//:errors",
        "@com_github_tliron_glsp//:glsp",
    ],
)

go_test(
    name = "git_test",
    srcs = ["handler_test.go"],
    embed = [":git"],
    deps = [
        "//pkg/poolside-helper/methods",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
