<script lang="ts">
  import { DEVICE_TOKEN_STORAGE_KEY } from "@poolsideai/remote-client";

  interface Props {
    onPaired: () => void;
  }

  const { onPaired }: Props = $props();

  function readScanCode(): string {
    return new URLSearchParams(window.location.hash.replace(/^#/, "")).get("pair") ?? "";
  }

  // A pairing QR encodes <url>#pair=<secret>. The secret starts a pending
  // request; the confirmation code is generated by the desktop and shown here.
  let scanCode = $state(readScanCode());
  let confirmationCode = $state("");
  let attemptToken = $state("");
  let error = $state("");
  let busy = $state(false);
  let waitingForDesktop = $state(false);
  let startedPairing = $state(false);

  function resetPairingState() {
    confirmationCode = "";
    attemptToken = "";
    error = "";
    busy = false;
    waitingForDesktop = false;
    startedPairing = false;
  }

  function defaultDeviceName(): string {
    const ua = navigator.userAgent;
    if (/iPhone/.test(ua)) return "iPhone";
    if (/iPad/.test(ua)) return "iPad";
    if (/Android/.test(ua)) return "Android phone";
    return "Remote browser";
  }

  async function openSession(deviceToken: string) {
    const sessionResp = await fetch("/api/session", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "same-origin",
      body: JSON.stringify({ deviceToken }),
    });
    if (!sessionResp.ok) {
      error = "Could not open a session";
      return;
    }
    window.location.hash = "";
    onPaired();
  }

  async function checkPairingComplete() {
    if (!attemptToken) return;
    try {
      const completeResp = await fetch("/api/pair/complete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "same-origin",
        body: JSON.stringify({ attemptToken }),
      });
      const completeBody = await completeResp.json();
      if (completeResp.status === 202) return;
      if (!completeResp.ok) {
        error = completeBody.error ?? "Pairing expired";
        waitingForDesktop = false;
        return;
      }
      localStorage.setItem(DEVICE_TOKEN_STORAGE_KEY, completeBody.deviceToken);
      await openSession(completeBody.deviceToken);
    } catch {
      error = "Could not reach the desktop. Are you on the same tailnet?";
    }
  }

  async function startPairing(force = false) {
    if (busy || (startedPairing && !force)) return;
    startedPairing = true;
    busy = true;
    error = "";
    try {
      const pairResp = await fetch("/api/pair", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "same-origin",
        body: JSON.stringify({ code: scanCode.trim(), deviceName: defaultDeviceName() }),
      });
      const pairBody = await pairResp.json();
      if (!pairResp.ok) {
        error = pairBody.error ?? "Pairing failed";
        return;
      }

      confirmationCode = pairBody.confirmationCode;
      attemptToken = pairBody.attemptToken;
      waitingForDesktop = true;
    } catch {
      error = "Could not reach the desktop. Are you on the same tailnet?";
    } finally {
      busy = false;
    }
  }

  // If we hold a device token from an earlier pairing, try a silent login.
  $effect(() => {
    const token = localStorage.getItem(DEVICE_TOKEN_STORAGE_KEY);
    if (!token) return;
    void (async () => {
      const resp = await fetch("/api/session", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "same-origin",
        body: JSON.stringify({ deviceToken: token }),
      });
      if (resp.ok) onPaired();
    })();
  });

  $effect(() => {
    const onHashChange = () => {
      const nextScanCode = readScanCode();
      if (nextScanCode === scanCode) return;
      scanCode = nextScanCode;
      resetPairingState();
    };
    window.addEventListener("hashchange", onHashChange);
    return () => window.removeEventListener("hashchange", onHashChange);
  });

  $effect(() => {
    if (!scanCode || attemptToken || busy || startedPairing) return;
    void startPairing();
  });

  $effect(() => {
    if (!waitingForDesktop || !attemptToken) return;
    void checkPairingComplete();
    const timer = setInterval(() => void checkPairingComplete(), 1500);
    return () => clearInterval(timer);
  });
</script>

<div class="pair-screen">
  <div class="pair-card">
    <h1>Poolside Remote</h1>
    {#if confirmationCode}
      <p>Enter this code in Poolside Assistant on your desktop.</p>
      <div class="confirmation-code">{confirmationCode}</div>
      <p class="waiting">Waiting for desktop approval…</p>
    {:else if scanCode}
      <p>Requesting approval from Poolside Assistant on your desktop.</p>
      <button type="button" disabled={busy} onclick={() => startPairing(true)}>
        {busy ? "Requesting…" : "Request approval"}
      </button>
    {:else}
      <p>
        Open <strong>Settings → Remote Access</strong> in Poolside Assistant and scan the QR code.
      </p>
    {/if}
    {#if error}
      <p class="pair-error">{error}</p>
    {/if}
  </div>
</div>

<style>
  .pair-screen {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100dvh;
    padding: 20px;
    background: var(--vscode-editor-background, #1b1f23);
    color: var(--vscode-foreground, #d1d5da);
  }

  .pair-card {
    max-width: 340px;
    width: 100%;
    text-align: center;
  }

  h1 {
    font-size: 22px;
    margin-bottom: 8px;
  }

  p {
    font-size: 14px;
    color: var(--vscode-descriptionForeground, #959da5);
    margin-bottom: 20px;
  }

  button {
    font-size: 16px;
    padding: 12px;
    border-radius: 8px;
    border: none;
    background: var(--vscode-button-background, #176f2c);
    color: var(--vscode-button-foreground, #dcffe4);
    cursor: pointer;
  }

  .confirmation-code {
    font-family: var(--vscode-editor-font-family, ui-monospace, SFMono-Regular, Menlo, monospace);
    font-size: 40px;
    font-weight: 700;
    letter-spacing: 6px;
    line-height: 1;
    margin: 24px 0 16px;
  }

  .waiting {
    margin-bottom: 0;
  }

  button:disabled {
    opacity: 0.6;
  }

  .pair-error {
    margin-top: 14px;
    color: var(--vscode-errorForeground, #f97583);
  }
</style>
