load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "secrets",
    srcs = ["server.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/handler/secrets",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/common/secrets",
        "//pkg/poolside-helper/methods",
        "@com_github_pkg_errors//:errors",
        "@com_github_tliron_glsp//:glsp",
    ],
)

go_test(
    name = "secrets_test",
    srcs = ["server_test.go"],
    embed = [":secrets"],
    deps = [
        "//pkg/common/secrets",
        "//pkg/poolside-helper/methods",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
