load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "lsptest",
__POOL_SYNTHETIC_IMPORT_BASELINE__
    srcs = ["lsptest.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/lsptest",
    visibility = ["//pkg/poolside-helper:__subpackages__"],
    deps = [
        "@com_github_sourcegraph_jsonrpc2//:jsonrpc2",
        "@com_github_tliron_glsp//:glsp",
    ],
)
