/**
 * Generated file.
 * Do not edit manually.
 */
export type IconName =
  | "admin"
  | "alert"
  | "apply"
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "arrow-down-circle"
  | "arrow-left-down"
  | "arrow-left"
  | "arrow-right"
  | "arrow-up-right"
  | "ask"
  | "block"
  | "bolt"
  | "bug"
  | "bulb"
  | "chats"
  | "checked"
  | "checkmark"
  | "chevron"
  | "clear"
  | "clock"
  | "close-circle"
  | "code"
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "command"
  | "compare"
  | "config"
  | "context"
  | "convert"
  | "copied"
  | "copy"
  | "cross"
  | "dark"
  | "debug"
  | "delete"
  | "demo"
  | "diff"
  | "discard"
  | "dot"
  | "edit"
  | "email"
  | "enter"
  | "error"
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "expand-both"
  | "expand-down"
  | "expand-up"
  | "export"
  | "eye-hidden"
  | "eye-visible"
  | "fast-forward"
  | "file-active"
  | "file-go"
  | "file"
  | "files-websites"
  | "files"
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "folder"
  | "gear"
  | "git-branch"
  | "git-commit"
  | "git-message"
  | "github"
  | "history"
  | "ide"
  | "info"
  | "key"
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "lab"
  | "leg"
  | "light"
  | "link"
  | "load-config"
  | "mcp-alert"
  | "mcp-ready"
  | "mcp"
  | "microphone"
  | "minus"
  | "more"
  | "new"
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "output"
  | "package"
  | "panel-bottom-closed"
  | "panel-bottom-open"
  | "pause"
  | "pencil"
  | "plan"
  | "plus-circle"
  | "plus"
  | "readme"
  | "reapply"
  | "regenerate"
  | "remote-access"
  | "restore"
  | "revert"
  | "review"
  | "rotate-ccw"
  | "roundel"
  | "run"
  | "sandbox"
  | "search"
  | "send"
  | "shield"
  | "sidebar-hide"
  | "sidebar-left-closed"
  | "sidebar-left-open"
  | "sidebar-right-closed"
  | "sidebar-right-open"
  | "sidebar-show"
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "slash"
  | "sparkles-slash"
  | "sparkles"
  | "star"
  | "start"
  | "step-above"
  | "step-below"
  | "stop"
  | "submit-additional-solid"
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "submit-solid"
__POOL_SYNTHETIC_IMPORT_BASELINE__
  | "symbol-code"
  | "symbol-type"
  | "symbol-value"
  | "symbols"
  | "system"
  | "target"
  | "task-new"
  | "task"
  | "terminal-active"
  | "terminal-done"
  | "terminal"
  | "thread"
  | "thumbs-down"
  | "thumbs-up"
  | "todo-complete"
  | "todo-pending"
  | "trash"
  | "user-small"
  | "user"
  | "vscode"
  | "wand"
  | "web";
