load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "servertest",
__POOL_SYNTHETIC_IMPORT_BASELINE__
    srcs = ["servertest.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/gotoolsinternal/jsonrpc2/servertest",
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/internal/gopls/gotoolsinternal/jsonrpc2"],
)

go_test(
    name = "servertest_test",
    srcs = ["servertest_test.go"],
    embed = [":servertest"],
    deps = ["//pkg/poolside-helper/internal/gopls/gotoolsinternal/jsonrpc2"],
)
