name: 'Setup'
__POOL_SYNTHETIC_IMPORT_BASELINE__
inputs:
  pnpm_install_args:
    description: '`pnpm install` args'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:    
    - name: Install pnpm
__POOL_SYNTHETIC_IMPORT_BASELINE__

    - name: Install Node.js
__POOL_SYNTHETIC_IMPORT_BASELINE__
      with:
        cache: "pnpm"
        node-version-file: ".tool-versions"
__POOL_SYNTHETIC_IMPORT_BASELINE__
    - name: Install dependencies
      shell: bash
      run: pnpm install ${{ inputs.pnpm_install_args }}
