name: 'Setup'
description: 'Setup pnpm with caching'
inputs:
  pnpm_install_args:
    description: '`pnpm install` args'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:    
    - name: Install pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        cache: "pnpm"
        node-version-file: ".tool-versions"

    - name: Install dependencies
      shell: bash
      run: pnpm install ${{ inputs.pnpm_install_args }}
