load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "secrets",
    srcs = [
        "error_codes.go",
        "keyring_store.go",
        "poolside_index.go",
        "poolside_secret_store.go",
        "secret_value.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/common/userconfig",
        "@com_github_google_uuid//:uuid",
        "@com_github_zalando_go_keyring//:go-keyring",
    ],
)

go_test(
    name = "secrets_test",
    srcs = [
        "keyring_store_test.go",
        "poolside_index_test.go",
        "poolside_secret_store_test.go",
        "secret_value_test.go",
    ],
    embed = [":secrets"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_zalando_go_keyring//:go-keyring",
    ],
)
