load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "keys",
    srcs = [
        "keys.go",
        "standard.go",
        "util.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/label"],
)

go_test(
    name = "keys_test",
    srcs = ["util_test.go"],
    embed = [":keys"],
)
