load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "logging",
    srcs = ["logging.go"],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/methods"],
)

go_test(
    name = "logging_test",
    srcs = ["logging_test.go"],
    embed = [":logging"],
    deps = ["//pkg/poolside-helper/methods"],
)
