load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "logging",
    srcs = ["logging.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/logging",
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/methods"],
)

go_test(
    name = "logging_test",
    srcs = ["logging_test.go"],
    embed = [":logging"],
    deps = ["//pkg/poolside-helper/methods"],
)
