__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
	"os"
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
	api := handler.New().OpenAPI()
	addr := os.Getenv("HELPER_OPENAPI_ADDR")
	if addr == "" {
		addr = ":8080"
	}
__POOL_SYNTHETIC_IMPORT_BASELINE__
	return http.ListenAndServe(addr, api.Adapter())
__POOL_SYNTHETIC_IMPORT_BASELINE__
