load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "release_lib",
    srcs = ["release.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/release",
    visibility = ["//visibility:private"],
    deps = [
        "@org_golang_x_mod//modfile",
        "@org_golang_x_mod//semver",
    ],
)

go_binary(
    name = "release",
    embed = [":release_lib"],
    visibility = ["//visibility:public"],
)
