load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "frob",
    srcs = ["frob.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/pkg/util/frob",
    visibility = ["//visibility:public"],
)

go_test(
    name = "frob_test",
    srcs = ["frob_test.go"],
    deps = [":frob"],
)
