load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cache",
    srcs = [
        "cache.go",
        "filterer.go",
        "fs_memoized.go",
        "fs_overlay.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/pkg/cache",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/poolside-helper/gopls/pkg/protocol",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/memoize",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/robustio",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/xcontext",
        "//pkg/poolside-helper/internal/gopls/pkg/file",
        "//pkg/poolside-helper/internal/gopls/pkg/label",
        "//pkg/poolside-helper/internal/gopls/pkg/util/bug",
    ],
)

go_test(
    name = "cache_test",
    srcs = ["fs_overlay_test.go"],
    embed = [":cache"],
    deps = [
        "//pkg/poolside-helper/gopls/pkg/protocol",
        "//pkg/poolside-helper/internal/gopls/pkg/file",
        "@com_github_samber_lo//:lo",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
