import DOMPurify from "dompurify";
import { encode } from "html-entities";

export function encodeMarkdownHtmlEntries(markdown: string) {
  const parts = markdown.split(
    /(```[\s\S]*?```|`[^`]*`|\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\)|\$[^$\n]*?\$)/g,
  );

  return parts
    .map((part, index) => {
      if (index % 2 === 0) {
        return encode(part, { mode: "nonAsciiPrintable", level: "html5" }).replace(/&amp;/g, "&");
      }
      return part;
    })
    .join("");
}

export function sanitizeMarkdownHtml(html: string): string {
  return DOMPurify.sanitize(html, {
    FORBID_TAGS: [
      "script",
      "noscript",
      "form",
      "input",
      "textarea",
      "select",
      "option",
      "button",
      "datalist",
      "output",
      "fieldset",
      "object",
      "embed",
      "applet",
      "iframe",
      "frame",
      "frameset",
      "base",
      "meta",
      "link",
      "style",
      "template",
      "slot",
      "canvas",
      "audio",
      "video",
      "track",
      "source",
    ],
    FORBID_ATTR: [
      "onload",
      "onerror",
      "onclick",
      "ondblclick",
      "onmousedown",
      "onmouseup",
      "onmouseover",
      "onmousemove",
      "onmouseout",
      "onmouseenter",
      "onmouseleave",
      "onkeydown",
      "onkeypress",
      "onkeyup",
      "onfocus",
      "onblur",
      "onchange",
      "onsubmit",
      "onreset",
      "onselect",
      "onabort",
      "oncanplay",
      "oncanplaythrough",
      "ondurationchange",
      "onemptied",
      "onended",
      "onloadeddata",
      "onloadedmetadata",
      "onloadstart",
      "onpause",
      "onplay",
      "onplaying",
      "onprogress",
      "onratechange",
      "onseeked",
      "onseeking",
      "onstalled",
      "onsuspend",
      "ontimeupdate",
      "onvolumechange",
      "onwaiting",
      "ontouchstart",
      "ontouchend",
      "ontouchmove",
      "ontouchcancel",
      "onwheel",
      "onscroll",
      "oncopy",
      "oncut",
      "onpaste",
      "oninput",
      "oninvalid",
      "onsearch",
      "ondrag",
      "ondragend",
      "ondragenter",
      "ondragleave",
      "ondragover",
      "ondragstart",
      "ondrop",
      "onanimationend",
      "onanimationiteration",
      "onanimationstart",
      "ontransitionend",
      "action",
      "method",
      "formaction",
      "formmethod",
      "formtarget",
      "autofocus",
      "autocomplete",
      "srcdoc",
      "sandbox",
      "csp",
      "integrity",
      "crossorigin",
    ],
    KEEP_CONTENT: true,
    ALLOWED_URI_REGEXP: /^(?:https?|mailto|data):\/?\/?/i,
    ALLOW_DATA_ATTR: true,
    ALLOW_UNKNOWN_PROTOCOLS: false,
    SAFE_FOR_TEMPLATES: false,
  });
}
