// Code generated by go-enum DO NOT EDIT.
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__

package methods

import (
	"errors"
	"fmt"
)

const (
	// ErrorEntityTypeSandboxDefinition is a ErrorEntityType of type sandbox_definition.
	ErrorEntityTypeSandboxDefinition ErrorEntityType = "sandbox_definition"
)

var ErrInvalidErrorEntityType = errors.New("not a valid ErrorEntityType")

// String implements the Stringer interface.
func (x ErrorEntityType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ErrorEntityType) IsValid() bool {
	_, err := ParseErrorEntityType(string(x))
	return err == nil
}

var _ErrorEntityTypeValue = map[string]ErrorEntityType{
	"sandbox_definition": ErrorEntityTypeSandboxDefinition,
}

// ParseErrorEntityType attempts to convert a string to a ErrorEntityType.
func ParseErrorEntityType(name string) (ErrorEntityType, error) {
	if x, ok := _ErrorEntityTypeValue[name]; ok {
		return x, nil
	}
	return ErrorEntityType(""), fmt.Errorf("%s is %w", name, ErrInvalidErrorEntityType)
}

const (
	// PoolsideErrorCodeEntityNotFound is a PoolsideErrorCode of type Entity_not_found.
	PoolsideErrorCodeEntityNotFound PoolsideErrorCode = iota + 1404
	// PoolsideErrorCodeConflict is a PoolsideErrorCode of type Conflict.
	PoolsideErrorCodeConflict PoolsideErrorCode = iota + 1408
	// PoolsideErrorCodeEntityInvalid is a PoolsideErrorCode of type Entity_invalid.
	PoolsideErrorCodeEntityInvalid PoolsideErrorCode = iota + 1420
	// PoolsideErrorCodeUserConfigInvalid is a PoolsideErrorCode of type User_config_invalid.
__POOL_SYNTHETIC_IMPORT_BASELINE__
	// PoolsideErrorCodeInternalError is a PoolsideErrorCode of type Internal_error.
	PoolsideErrorCodeInternalError PoolsideErrorCode = iota + 1496
	// PoolsideErrorCodeAgentInstallFailed is a PoolsideErrorCode of type Agent_install_failed.
	PoolsideErrorCodeAgentInstallFailed PoolsideErrorCode = iota + 1497
)

const _PoolsideErrorCodeName = "entity_not_foundconflictentity_invaliduser_config_invalidinternal_erroragent_install_failed"

var _PoolsideErrorCodeMap = map[PoolsideErrorCode]string{
	PoolsideErrorCodeEntityNotFound:     _PoolsideErrorCodeName[0:16],
	PoolsideErrorCodeConflict:           _PoolsideErrorCodeName[16:24],
	PoolsideErrorCodeEntityInvalid:      _PoolsideErrorCodeName[24:38],
	PoolsideErrorCodeUserConfigInvalid:  _PoolsideErrorCodeName[38:57],
	PoolsideErrorCodeInternalError:      _PoolsideErrorCodeName[57:71],
	PoolsideErrorCodeAgentInstallFailed: _PoolsideErrorCodeName[71:91],
}

// String implements the Stringer interface.
func (x PoolsideErrorCode) String() string {
	if str, ok := _PoolsideErrorCodeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("PoolsideErrorCode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PoolsideErrorCode) IsValid() bool {
	_, ok := _PoolsideErrorCodeMap[x]
	return ok
}

var _PoolsideErrorCodeValue = map[string]PoolsideErrorCode{
	_PoolsideErrorCodeName[0:16]:  PoolsideErrorCodeEntityNotFound,
	_PoolsideErrorCodeName[16:24]: PoolsideErrorCodeConflict,
	_PoolsideErrorCodeName[24:38]: PoolsideErrorCodeEntityInvalid,
	_PoolsideErrorCodeName[38:57]: PoolsideErrorCodeUserConfigInvalid,
	_PoolsideErrorCodeName[57:71]: PoolsideErrorCodeInternalError,
	_PoolsideErrorCodeName[71:91]: PoolsideErrorCodeAgentInstallFailed,
}
