load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "diff",
    srcs = [
        "diff.go",
        "ndiff.go",
        "unified.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/gotoolsinternal/diff",
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/internal/gopls/gotoolsinternal/diff/lcs"],
)

go_test(
    name = "diff_test",
    srcs = [
        "diff_test.go",
        "export_test.go",
    ],
    embed = [":diff"],
    deps = [
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/diff/difftest",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/testenv",
    ],
)
