load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "myers",
    srcs = ["diff.go"],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/internal/gopls/gotoolsinternal/diff"],
)

go_test(
    name = "myers_test",
    srcs = ["diff_test.go"],
    deps = [
        ":myers",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/diff/difftest",
    ],
)
