load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "metric",
    srcs = [
        "data.go",
        "exporter.go",
        "info.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/core",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/keys",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/label",
    ],
)
