load("@rules_go//go:def.bzl", "go_library", "go_test")
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
    importpath = "github.com/poolsideai/assistant/pkg/common/version",
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
        "github.com/poolsideai/assistant/pkg/common/version.Commit": "{GIT_COMMIT}",
        "github.com/poolsideai/assistant/pkg/common/version.BuildTime": "{BUILD_TIME}",
        "github.com/poolsideai/assistant/pkg/common/version.Tag": "{STABLE_VERSION_TAG}",
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__

go_test(
    name = "version_test",
    srcs = ["version_test.go"],
    embed = [":version"],
    deps = ["@com_github_stretchr_testify//assert"],
)
