load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "userconfig",
    srcs = [
        "doc.go",
        "path.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/common/userconfig",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_adrg_xdg//:xdg",
    ],
)
