load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "label",
    srcs = ["label.go"],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
)

go_test(
    name = "label_test",
    srcs = ["label_test.go"],
    deps = [
        ":label",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/keys",
    ],
)
