__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
  local addr="${HELPER_OPENAPI_ADDR:-127.0.0.1:18080}"
  local schema_url="http://${addr}/openapi.yaml"

__POOL_SYNTHETIC_IMPORT_BASELINE__
  HELPER_OPENAPI_ADDR="${addr}" go run -tags=fts5 ../../../cmd/poolside-helper openapi &
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
  while ! curl --fail --silent --output /dev/null "${schema_url}"; do
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
  # Intentionally not using turbo because it doesn't know about changes in the source go files
  LOCAL_SCHEMA="${schema_url}" pnpm -F @poolsideai/helperapi codegen
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
  local addr="${HELPER_OPENAPI_ADDR:-127.0.0.1:18080}"
  local port="${addr##*:}"
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
main "$@"
