__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
using Poolside.Assistant.WebViewInfrastructure;
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
        internal TasksWebViewCommunicator(ChromiumWebBrowser browser, PoolsideTaskDTO task, PoolsideTaskVersionDTO version)
            : base(browser, $"this.POOLSIDE_INITIAL_TASK_STATE = {JsonConvert.SerializeObject(task)};\n" +
                  (version != null ? $"this.POOLSIDE_SELECTED_TASK_VERSION_ID = \"{version.id}\";\n" : ""))
        {
        }
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
