load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "core",
    srcs = [
        "event.go",
        "export.go",
        "fast.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/keys",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/label",
    ],
)
