package ignore

var (
	defaultGitIgnoreStrings = []string{
		// Version Control
		".git/",
		".svn/",
		".hg/",
		".bzr/",
		"CVS/",

		// Dependencies
		"node_modules/",
		"vendor/",
		".venv/",
		"__pycache__/",
		"*.pyc",
		"*.pyo",
		"*.pyd",
		".pytest_cache/",

		// Build outputs
		"dist/",
		"build/",
		"*.exe",
		"*.dll",
		"*.so",
		"*.dylib",

		// IDE and Editor files
		".idea/",
		".vscode/",
		"*.swp",
		"*.swo",
		".DS_Store",
		"Thumbs.db",

		// Logs and temporary files
		"*.log",
		"*.tmp",
		"*.temp",
		".cache/",
		".pytest_cache/",
		".Trash",

		// Package manager files
		"yarn.lock",
		"package-lock.json",
		"poetry.lock",
		"Pipfile.lock",
		"go.sum",
		"gradle.properties",
		"local.properties",
		"keystore.properties",
		"build.gradle",
		"Podfile.lock",
		"Cartfile.resolved",
		"composer.lock",
		"Gemfile.lock",
		"mix.lock",
		"requirements.txt",
		"cargo.lock",

		// Coverage and test reports
		"coverage/",
		".coverage",
		"htmlcov/",
	}

	defaultSensitiveIgnoreStrings = []string{
		// Environment and Configuration Files
		".env*",
		"web.config",
		"wp-config.php",

		// Shell Configuration Files
		".bash_aliases",
		".bash_profile",
		".bash_history",
		".bash_logout",
		".bashrc",
		".cshrc",
		".inputrc",
		".kshrc",
		".tcshrc",
		".profile",
		".shell_history",
		".sh_history",
		".fish_history",
		"config.fish",
		".fishrc",
		".config/fish/config.fish",
		".config/fish/fish_variables",
		".config/bash/bashrc",
		".config/zsh/.zshrc",
		".zlogin",
		".zlogout",
		".zprofile",
		".zsh_aliases",
		".zsh_history",
		".zshrc",

		// API Keys and Tokens
		".aws/credentials",
		".aws/config",
		".azure/credentials",
		"credentials.json",
		"client_secret.json",
		"client_secrets.json",
		".dockercfg",
		".docker/config.json",
		"gcloud/credentials.db",
		"gcloud/access_tokens.db",
		".curlrc",
		".netrc",
		".npmrc",
		".pypirc",
		".yarnrc",
		"terraform.tfvars",
		"terraform.tfstate",
		".terraform.tfstate.lock.info",
		".terraformrc",

		// SSH and Cryptographic Keys
		"*.asc",
		"*.cer",
		"*.csr",
		"*.crt",
		"*.der",
		"*.gpg",
		"*.jks",
		"*.keystore",
		"*.key",
		"*.p12",
		"*.pem",
		"*.pfx",
		"*.pkcs12",
		"authorized_keys",
		"id_rsa",
		"id_dsa",
		"id_ecdsa",
		"id_ed25519",
		".gnupg/",
		".gnupg/secring.gpg",
		"known_hosts",
		".kube/config",
		"ssh_config",
		"sshd_config",
		"ssh_host_*_key",
		".ssh/config",
		".ssh/id_rsa",
		".ssh/id_dsa",
		".ssh/id_ecdsa",
		".ssh/id_ed25519",

		// Database Files and Credentials
		"*.accdb",
		"*.db",
		"*.dump",
		"*.mdb",
		"*.psql",
		"*.sqlite",
		"*.sqlite3",
		"credentials.ini",
		"mongod.conf",
		"pgpass",
		".pgpass",
		"redis.conf",

		// Passwords and Credential Stores
		".htaccess",
		".htpasswd",
		"master.key",
		"production.key",
		"secrets.yml",
		"secrets.yaml",
		"secrets.json",
		"secret_token.rb",
		"secret_key_base.rb",

		// Container and Deployment Files
		".dockerenv",
		"helm/secrets.yaml",
		"helm/values.yaml",
		"k8s/secrets.yaml",
		"kubernetes/secrets.yaml",

		// Cloud and Infrastructure
		".boto",
		".s3cfg",
		"terragrunt.hcl",

		// Blockchain and Cryptocurrency
		".bitcoin/",
		".ethereum/",
		"mnemonic.txt",
		"private-key.txt",
		"seed-phrase.txt",
		"wallet.dat",
		"wallet.key",
	}
)
