__POOL_SYNTHETIC_IMPORT_BASELINE__
echo GIT_COMMIT "${GITHUB_SHA:-$(git rev-parse --short HEAD)}"
__POOL_SYNTHETIC_IMPORT_BASELINE__
__POOL_SYNTHETIC_IMPORT_BASELINE__
echo GIT_BRANCH "${GITHUB_REF_NAME:-$(git symbolic-ref --short HEAD 2>/dev/null || echo "")}"
if [ "${GITHUB_REF_TYPE:-}" = "tag" ]; then
    echo GIT_TAG "$GITHUB_REF_NAME"
__POOL_SYNTHETIC_IMPORT_BASELINE__
