load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "ocagent",
    srcs = [
        "metrics.go",
        "ocagent.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export/ocagent",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/core",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export/metric",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export/ocagent/wire",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/keys",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/label",
    ],
)

go_test(
    name = "ocagent_test",
    srcs = [
        "metrics_test.go",
        "ocagent_test.go",
        "trace_test.go",
    ],
    deps = [
        ":ocagent",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/core",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/export/metric",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/keys",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/event/label",
    ],
)
