load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fake",
__POOL_SYNTHETIC_IMPORT_BASELINE__
    srcs = [
        "client.go",
        "doc.go",
        "edit.go",
        "editor.go",
        "proxy.go",
        "sandbox.go",
        "workdir.go",
        "workdir_windows.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/poolside-helper/gopls/pkg/protocol",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/diff",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/jsonrpc2",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/jsonrpc2/servertest",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/proxydir",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/robustio",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/testenv",
        "//pkg/poolside-helper/internal/gopls/gotoolsinternal/xcontext",
        "//pkg/poolside-helper/internal/gopls/pkg/test/integration/fake/glob",
        "//pkg/poolside-helper/internal/gopls/pkg/util/bug",
        "//pkg/poolside-helper/internal/gopls/pkg/util/pathutil",
        "//pkg/poolside-helper/internal/gopls/pkg/util/slices",
        "@org_golang_x_tools//txtar",
    ],
)

go_test(
    name = "fake_test",
    srcs = [
        "edit_test.go",
        "editor_test.go",
        "workdir_test.go",
    ],
    embed = [":fake"],
    deps = [
        "//pkg/poolside-helper/gopls/pkg/protocol",
        "@com_github_google_go_cmp//cmp",
    ],
)
