load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "wire",
    srcs = [
        "common.go",
        "core.go",
        "metrics.go",
        "trace.go",
    ],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
)

go_test(
    name = "wire_test",
    srcs = ["metrics_test.go"],
    embed = [":wire"],
)
