load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "file",
    srcs = [
        "file.go",
        "hash.go",
        "kind.go",
        "modification.go",
    ],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/pkg/file",
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/gopls/pkg/protocol"],
)
