load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "goroutine",
    srcs = ["goroutine.go"],
    importpath = "github.com/poolsideai/assistant/pkg/common/goroutine",
    visibility = ["//visibility:public"],
    deps = ["@com_github_pkg_errors//:errors"],
)

go_test(
    name = "goroutine_test",
    srcs = ["goroutine_test.go"],
    embed = [":goroutine"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
