load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "stacktest",
__POOL_SYNTHETIC_IMPORT_BASELINE__
    srcs = ["stacktest.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/internal/gopls/gotoolsinternal/stack/stacktest",
    visibility = ["//visibility:public"],
    deps = ["//pkg/poolside-helper/internal/gopls/gotoolsinternal/stack"],
)
