load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "afero2billy",
    srcs = ["wrapper.go"],
    importpath = "github.com/poolsideai/assistant/pkg/workspace/afero2billy",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_go_git_go_billy_v5//:go-billy",
        "@com_github_go_git_go_billy_v5//helper/chroot",
        "@com_github_go_git_go_billy_v5//util",
        "@com_github_spf13_afero//:afero",
    ],
)
