load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "server",
    srcs = ["server.go"],
__POOL_SYNTHETIC_IMPORT_BASELINE__
    visibility = ["//visibility:public"],
    deps = [
__POOL_SYNTHETIC_IMPORT_BASELINE__
        "//pkg/poolside-helper/internal/shellenv",
        "@com_github_tliron_glsp//server",
    ],
)
