load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "server",
    srcs = ["server.go"],
    importpath = "github.com/poolsideai/assistant/pkg/poolside-helper/server",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/poolside-helper/internal/handler",
        "//pkg/poolside-helper/internal/shellenv",
        "@com_github_tliron_glsp//server",
    ],
)
