load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "git",
    srcs = ["git.go"],
    importpath = "github.com/poolsideai/assistant/pkg/git",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/workspace/afero2billy",
        "@com_github_go_git_go_git_v5//:go-git",
        "@com_github_go_git_go_git_v5//utils/ioutil",
        "@com_github_spf13_afero//:afero",
    ],
)

go_test(
    name = "git_test",
    srcs = ["git_test.go"],
    embed = [":git"],
    deps = [
        "@com_github_go_git_go_git_v5//:go-git",
        "@com_github_spf13_afero//:afero",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
